@startuml
hide empty description
state Available
state Reserved
state InUse
state Maintenance
Available --> Reserved : reserve
Reserved --> InUse : unlock
InUse --> Available : return
Maintenance --> Available : repaired
@enduml
